### ISSUE TITLE
Code project html file

### ISSUE THREAD

**Issue by brianliu1412** [cse110-spr23-group18/cse110-sp23-group18#13]
Translate figma designs to html. 

### Things to keep in mind:
Use css selectors (i.e. classnames, id tags etc. ) to ensure that the people working on the css.

### file naming conventions:

- Use descriptive css selector names. 
- An example would be image-1, tea-leaf-prompt, tea-leaf-reading, reading-response.
- Use hyphens to indicate spaces, and all lowercase.

**Comment by CatFish47** [comment]
Have been split into issues #36 and #37
