### ISSUE TITLE
Add deploy previews

### ISSUE THREAD

**Issue by CatFish47** [cse110-spr23-group18/cse110-sp23-group18#14]
Every time a PR is made, create a preview of the build (via something like netlify) so that someone reviewing the build can look at the preview.

**Comment by brianliu1412** [comment]
Added deploy previews with netlify:

- I created a google account to setup the team netlify account
- Passwords doc: [link](https://docs.google.com/document/d/1og6L9dVQx9kIncxr7cat9y9qubj4cYzlojsybDgGLU4/edit?usp=sharing)
- I created prod as the main deploy branch with deploy previews on every other branch in the repo.
