### ISSUE TITLE
Generate Visual and Audio Assets

### ISSUE THREAD

**Issue by brianliu1412** [cse110-spr23-group18/cse110-sp23-group18#20]
### Due Date: (03/18/23 ###

Description of Issue:

Finalize Creative Assets for mobile first (at least) so that dev can start working on product.

**Comment by brianliu1412** [comment]
Link to Asset Checklist: [Google Docs](https://docs.google.com/document/d/1Ddm7LtsTBy6bt6XGycTQjVVUitqHTlt-lxmhuUSOFaQ/edit)

**Comment by CatFish47** [comment]
Some assets uploaded on branch `branch20-createassets`

**Comment by CatFish47** [comment]
Closed with PR #23
