### ISSUE TITLE
Create Changelog 

### ISSUE THREAD

**Issue by brianliu1412** [cse110-spr23-group18/cse110-sp23-group18#31]
### Due Date: (05/26/23) ###

Description of Issue:
Research and Create a Changelog which can possibly be automated.

**Comment by brianliu1412** [comment]
Thinking about using this:
[Auto Changelog](https://github.com/cookpete/auto-changelog)

**Comment by CatFish47** [comment]
@brianliu1412 is this done?

**Comment by brianliu1412** [comment]
@CatFish47 tentative yes, also our last commit to prod didn't produce anything so idk

**Comment by brianliu1412** [comment]
Changelogs working, tested on Dev branch. Will Close Issue
