### ISSUE TITLE
Create CSS/JS file for Animation of Elements and Handling Interactions

### ISSUE THREAD

**Issue by ouyangca** [cse110-spr23-group18/cse110-sp23-group18#36]
Description of Issue:
Create a javascript file for each frame, corresponding to the HTML files. Tentative animations: 

- enlarging and highlighting tea leaves jars when the mouse hovers over 
- using translation animation to simulate the pouring of the teapot
- setting the gif for the boiling kettle to loop only once
- get the device information and change the style of the webpage accordingly. First, focus on the mobile version, and later adjust for the desktop.

Urgency: High (necessary for the MVP)
Due Date: Before the end of Week 8  (Friday, May 25 2023)

**Comment by brianliu1412** [comment]
Done!
