### ISSUE TITLE
Implement Audio from Assets

### ISSUE THREAD

**Issue by brianliu1412** [cse110-spr23-group18/cse110-sp23-group18#64]
### Priority: Med ###

Description of Issue:

We need to add: 

- [x] Background Music
- [x] Teapot steaming / whistling
- [x] Tea pouring
- [x] Tea Drinking noise
- [x] Tea Draining / Mystical Sound

**Comment by KristinShuyiHan** [comment]
Have finished adding all the audio assets to our frames.
